### ISSUE TITLE
[Request-Parser]: Add WHERE clause

### ISSUE THREAD

**Issue by johannesschobel** [prisma-utils/prisma-utils#18]
**Is your feature request related to a problem? Please describe.**

The `request-parser` should allow for processing `where` (i.e., `filter`) query params and automatically parse them to a prisma compliant call.

**Affected Package**
This is a feature request for which package?
- [ ] nestjs-prisma
- [ ] prismerge
- [x] request-parser

**Describe the solution you'd like**

Don't know, which format for the `where` clause would be appropriate. i was thinking about a serialized json-object that can be parsed again. not sure if this is a good idea.

**Comment by ChristopherCapito** [comment]
Maybe an ODATA-like filter syntax might be a good idea?

**Comment by ChristopherCapito** [comment]
Pretty straight forward, and the syntax is not bad. Would just have to make sure to have it properly encoded if needs be

**Comment by johannesschobel** [comment]
this has been implemented in #41
