### ISSUE TITLE
Prismerge ES and CJS module warning

### ISSUE THREAD

**Issue by Nukiloco** [prisma-utils/prisma-utils#20]
**Describe the bug**
```
@prisma-utils/prismerge doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

This error appears when running a vite server with prismerge installed as a developer dependency.

**Affected Package** 
Which package are you referring to?
- [ ] nestjs-prisma
- [x] prismerge
- [ ] request-parser

**To Reproduce**
Read above.

**Expected behavior**
I expect the warning not to appear.

**Versions (please complete the following information):**
 - OS: Windows 10
 - Version: 1.5.2
 - NodeJS: v16.14.1
 - PNPM: 6.11.0

**Comment by johannesschobel** [comment]
Dear @Nukiloco , thanks for raising this issue.
do we really need a `type: module` or would a `type: commonjs` also work out? just thinking

**Comment by johannesschobel** [comment]
try the latest version of `prismerge` ( v1.6.2): https://www.npmjs.com/package/@prisma-utils/prismerge/v/1.6.2 
It is now exported as `commonjs` so you can run it from the console.
Can you give feedback if this works for you?

**Comment by johannesschobel** [comment]
Dear @Nukiloco , is this issue solved? Please close if the provided solution works for you
