### ISSUE TITLE
Support multi environment for prismerge

### ISSUE THREAD

**Issue by kerituni12** [prisma-utils/prisma-utils#23]
**Is your feature request related to a problem? Please describe.**
Exclude specific file when run prismerge with different options

**Affected Package**
This is a feature request for which package?
- [ ] nestjs-prisma
- [x] prismerge
- [ ] request-parser

**Describe the solution you'd like**
I using prisma-nestjs-graphql as prisma generator for graphql type and have a file config for it and include in prismerge.json . But I only want to run it in dev environment.

**Describe alternatives you've considered**
Currently i must create two prismerge.json file for two environment. Instead of that i want to have config option in one prismerge file and run it with options via cli

**Comment by johannesschobel** [comment]
would it help to add an additional flag, like `-a app1, app2` where you can specify the apps you want to generate?

Your `prismerge.json` file would look like this:

```json
{
  "dev": {
    "inputs": [
      "./libs/core/prisma/base.prisma",
      "./libs/user/prisma/user.prisma",
      "./libs/article/prisma/article.prisma",
      "./libs/x/prisma/x.prisma",
      "./libs/y/prisma/y.prisma",
      "./libs/z/prisma/z.prisma"
    ],
    "output": "./prisma/schema.prisma"
  },
 "prod": {
    "inputs": [
      "./libs/core/prisma/base.prisma",
      "./libs/user/prisma/user.prisma",
      "./libs/article/prisma/article.prisma"
    ],
    "output": "./prisma/schema.prisma"
  }
}
```

and then call

```bash
npx prismerge -a dev
```

what do you think?
all the best

**Comment by johannesschobel** [comment]
Dear @kerituni12 ,

try the latest version of `PrisMerge` (v 1.7.0) with the following feature:
To exclude (!!!) a specific app from being processed, simply use the `-eA appname` flag via the CLI.

For example, if you have 5 different apps (or environment - whatever you would like to call them), you can exclude one, by calling

```bash
npx prismerge -eA prod
```

Hope this helps, all the best

**Comment by johannesschobel** [comment]
The feature is also documented here:
https://github.com/prisma-utils/prisma-utils/tree/main/libs/prismerge#apps

**Comment by kerituni12** [comment]
Great
