### ISSUE TITLE
Support generating exports for prisma-crud-generator

### ISSUE THREAD

**Issue by kdawgwilk** [prisma-utils/prisma-utils#24]
**Is your feature request related to a problem? Please describe.**
When you generate services it would be nice if you could enable the generation of index files with exports

**Affected Package**
This is a feature request for which package?
- [ ] nestjs-prisma
- [ ] prismerge
- [ ] request-parser
- [x] prisma-crud-generator

**Describe the solution you'd like**
a flag you can pass to the generator to enable the generation of index file(s) with exports

**Describe alternatives you've considered**
Manually maintaining an index files that exports the services

**Additional context**

**Comment by johannesschobel** [comment]
Dear @kdawgwilk ,
thanks for the feature request. I actually thought about this myself, but wasn't sure about where to store / save the `index.ts` file (barrel file).

For example, i use this package in a `nrwl/nx` workspace, therefore, i have multiple libraries, where respective service is exported to (i.e., i use the `#{model}` placeholder in the output path!). Likewise, each library should have its own barrel file - but where?

Finally, i once read some kind of "best practice" where they clearly stated, that each library should have only one barrel file, where all exports are listed.

For me, the `crud services` are also completely "internal" and should not be exposed to the outside / other modules.

What kind of solution would help with your issues?
All the best

**Comment by kdawgwilk** [comment]
I have a NestJS workspace and a `@lib/prisma` library that I would like to put these generated services in so my NestJS application can import them to be used/extended. I can manually manage the exports for now so its not a huge problem but I agree its a tricky problem

**Comment by johannesschobel** [comment]
Dear @kdawgwilk ,

you can also try using the `nestjs-prisma` package from this repository - this may also help you in implementing prisma in a nestjs application. Shameless advertisement, haha ;)

However, back to the topic:
In my project, i use it the following way:
I have a regular controller, that validates the input and so on, and then calls a respective service. This service, in turn, maps the input (that is received from the controller) to a prisma object (i.e., a `UserCreateInput` or whatever this is called) and calls the auto-generated `user.crud.service.ts` file, which does all the magic. The response bubbles back up and is returned to the client.

Hope this helps

**Comment by johannesschobel** [comment]
i will close this issue for now.. feel free to repopen, if you have any additional questions or ideas how to properly solve this problem ;)
