### ISSUE TITLE
prisma-crud-generator does not support models with camelCased names

### ISSUE THREAD

**Issue by kdawgwilk** [prisma-utils/prisma-utils#26]
**Describe the bug**
I have prisma models that are more than 1 word such as `FavoriteSkill` and currently the templating system only supports `#{Model}`, `#(model}`, and `#{MODEL}` formats but the prisma generated client exposes the model clients using `camelCase` so there is no way to template in those models

**Affected Package** 
Which package are you referring to?
- [ ] nestjs-prisma
- [ ] prismerge
- [ ] request-parser
- [x] prisma-crud-generator

**To Reproduce**
1. Create Prisma model `FavoriteSkill`
2. Add prisma-crud-generator to prisma schema
3. run `npm run prisma generate`
4. View generated service definition and see typescript error

<img width="784" alt="image" src="https://user-images.githubusercontent.com/7799267/184183169-379a2ccd-ed9e-4534-a03c-61e037822b76.png">

**Expected behavior**

We need a way to either indicate to the templating system to use camelCasing or not use `toLowerCase()` when interpolating `#{model}`

**Comment by johannesschobel** [comment]
Dear @kdawgwilk ,
thank you very much for mentioning this issue. I have added the requested fix and updated the stubs accordingly. can you please try and give feedback with the latest version (v. 1.0.3)?

thank you so much and all the best,
Johannes

**Comment by kdawgwilk** [comment]
Tried this out and its working great! Thanks for the quick response ❤️
