### ISSUE TITLE
Prismerge: Linting fragments in editor

### ISSUE THREAD

**Issue by julianwagle** [prisma-utils/prisma-utils#33]
**Affected Package**
This is a feature request for which package?
- [ ] nestjs-prisma
- [X] prismerge
- [ ] request-parser

I am not sure if this feature already exists, but is there a way to support accurate linting in the IDE (mine is VS Code) for Prismerge and its fragments. For example, if I create a fragment file as shown below:

id.prisma.fragment
```
id String @id @default(uuid())
createdAt DateTime @default(now())
updatedAt DateTime @updatedAt
```

as then add in the fragment as shown below:

nouns.prisma
```
model Person {
    ...id
}

model Place {
    ...id
}

model Thing {
    ...id
}
```

Each of the references to `...id` displays the infamous "red squiggly line"

I have found a temporary workaround by adding the following line to the top of each fragment:

```
// This is a fragment. Do not rm this line! Things will break if you do.
```
(technically, the line above could remain an empty line ... i just felt the above was more explicit)

and then adding a comment marker to each fragment reference as shown below:

```
model Person {
    // ...id
}
```

This will remove the red squiggle and return a valid schema on generation but there is still no way to know that the schema is valid prior to generation. Not a huge deal breaker but would be nice to know if I am missing something obvious that already exists. Thanks!

**Comment by johannesschobel** [comment]
Dear @julianwagle ,

thank you very much for raising this issue. I am aware, that the `fragments` are not valid prisma documents, and the `...` syntax i used to include the fragments neither.
However, changing this behaviour would require some dirty hacks (as you found out) or changing the VSCode prisma language server - which is out of scope for me ;)

My current approach is as follows:
1) create the fragements
2) include it in a real model
3) run `npx prismerge` to create the full prisma file
4) check for errors ;)
5) start over if some errors occur

Not the best approach, but the others are currently out of scope for this package.

I will close this issue for now, ok?
All the best,
Johannes
