### ISSUE TITLE
Support glob for Prismerge input files

### ISSUE THREAD

**Issue by KeisukeYamashita** [prisma-utils/prisma-utils#9]
## WHY

In many cases, we want to merge all Prisma schemas based on patterns.
In such use cases, the glob pattern allows users to flexibly specify the schema they wish to merge.

## Example

```json
{
  "app1": {
    "inputs": [
      "./apps/api/src/prisma/*.prisma"  <- Here
    ],
```

**Comment by johannesschobel** [comment]
Dear @KeisukeYamashita ,

thanks for the feature request - i will take a look at it. Should not be that complicated / complex. However, i am quite busy till the end of month, so don't expect this feature before july ;)

All the best

**Comment by KeisukeYamashita** [comment]
@johannesschobel Thank you for your quick reply! I've raised a PR for this 👉 https://github.com/prisma-utils/prisma-utils/pull/10

Hope this will help, thank you in advance.

**Comment by johannesschobel** [comment]
i already implemented the feature, as i had some waiting time.. 
just running the CI pipeline and then releasing it to NPM as a new version.

sorry, i just saw that you have raised a PR :( My bad..

**Comment by johannesschobel** [comment]
new version has been released `@prisma-utils/prismerge v1.3.1` with `glob` support

**Comment by KeisukeYamashita** [comment]
I see! Thank you very much!!!

**Comment by johannesschobel** [comment]
I hope this suits your needs.. if you have additional ideas, please feel free to tell it submit a PR 🥳
